api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('createchat', views.createChat, name='createchat'),
    path('sendcode', views.sendVerificationCode, name='sendcode'),
    path('registeruser', views.registerUser, name='registeruser'),
    path('deletenotification', views.deleteNotification, name='deletenotification'),
    path('getevents', views.getEvents, name='getevents'),
    path('changesettings', views.changeSettings, name='changesettings'),
    path('refreshTreatmentStatus', views.refreshTreatmentStatus, name='refreshTreatmentStatus'),
    path('addCurrProcedure', views.addCurrProcedure, name='addCurrProcedure'),
    path('closeTreatment', views.closeTreatment, name='closeTreatment'),
    path('setDoctorRating', views.setDoctorRating, name='setDoctorRating'),
    path('get_current_procedure_info', views.getCurrentProcedureInfo, name='get_current_procedure_info')
]

med/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.default, name='default'),
    path('index', views.index, name='index'),
    path('registration', views.reg, name='reg'),
    path('dashboard', views.dash, name='dash'),
    path('logout', views.logout_view, name='logout'),
    path('chats', views.chats, name='chats'),
    path('chat', views.chat, name='chat'),
    path('notifications', views.notifications, name='notifications'),
    path('calendar', views.calendar, name='calendar'),
    path('create_event', views.create_event, name='create_event'),
    path('account', views.account, name='account'),
    path('settings', views.settings, name='settings'),
    path('create_treatment', views.create_treatment, name='create_treatment'),
    path('accept_treatment', views.accept_treatment, name='accept_treatment'),
    #path('profile', views.profile, name='profile'),
    path('user_treatment_panel', views.user_treatment_panel, name='user_treatment_panel'),
    path('my_patients', views.my_patients, name='my_patients'),
    path('my_treatments', views.my_treatments, name='my_treatments'),
    path('search', views.search, name='search'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from mysite.settings import MEDIA_ROOT


urlpatterns = [
    path('', include('med.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls)
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

med/models.py
from pyexpat import model
from tabnanny import verbose
from django.db import models
# from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django.contrib.postgres.fields import ArrayField
from numpy import mean


class User(AbstractUser):
    # first_name, last_name
    avatar = models.ImageField(upload_to='avatars/', default='avatars/default_avatar.jpg')
    username = None
    is_patient = models.BooleanField(default=False)
    is_clinic = models.BooleanField(default=False)
    is_doctor = models.BooleanField(default=False)
    email = models.EmailField(unique=True)
    USERNAME_FIELD = 'email'
    phone = models.CharField(max_length=20)
    REQUIRED_FIELDS = []
    patronymic = models.CharField(max_length=25, null=True, blank=True)


class Patient(models.Model):
    extra = models.TextField(default="")
    passport_number = models.CharField(null=True, max_length=4, default=None)
    passport_series = models.CharField(null=True, max_length=6, default=None)
    snils = models.CharField(null=True, max_length=11, default=None)
    age = models.CharField(null=True, default=None, max_length=3)
    allergies = models.TextField(null=True, default=None)
    diseases = models.TextField(null=True, default=None)

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True)


class Clinic(models.Model):
    specialization = models.TextField(default="")
    address = models.CharField(max_length=1000, default="")
    addressLink = models.URLField(null=True, blank=True)
    extra = models.TextField(default="")
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key = True)


class Doctor(models.Model):
    specialization = models.TextField(default="")
    extra = models.TextField(default="")
    # passport_number = models.CharField(null=True, max_length=4, default=None)
    # passport_series = models.CharField(null=True, max_length=6, default=None)
    license = models.CharField(null=True, max_length=1000, default=None)
    license_date = models.DateTimeField(null=True, default=None)
    experience = models.CharField(null=True, default=None, max_length=100)

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key = True)
    
    clinics = models.ManyToManyField(Clinic)

    class Meta:
        verbose_name = 'Доктор'

    def getAverageRating(self):
        _ = Rating.objects.filter(owner=self.user.id)
        if _:
            _ = [r.rating for r in _]
            return '{:.1f}'.format(mean(_))
            
        else:
            return None

class Schedule(models.Model):
    doctor = models.OneToOneField(Doctor, on_delete = models.CASCADE)
    monday = ArrayField(models.TimeField(auto_now=False, auto_now_add=False), size=2, null=True)
    tuesday = ArrayField(models.TimeField(auto_now=False, auto_now_add=False), size=2, null=True)
    wednesday = ArrayField(models.TimeField(auto_now=False, auto_now_add=False), size=2, null=True)
    thursday = ArrayField(models.TimeField(auto_now=False, auto_now_add=False), size=2, null=True)
    friday = ArrayField(models.TimeField(auto_now=False, auto_now_add=False), size=2, null=True)
    saturday = ArrayField(models.TimeField(auto_now=False, auto_now_add=False), size=2, null=True)
    sunday = ArrayField(models.TimeField(auto_now=False, auto_now_add=False), size=2, null=True)


class Chat(models.Model):
    users = models.ManyToManyField(User)
    creationDate = models.DateTimeField(auto_now_add=True)


class Message(models.Model):
    chat = models.ForeignKey(Chat, on_delete = models.CASCADE)
    text = models.TextField()
    sender = models.IntegerField()
    creationDate = models.DateTimeField(auto_now_add=True)


class Event(models.Model):
    # 0 - default, 1 - прием таблеток, 2 - прием у врача, 3 - процедура, 4 - иные события
    type = models.CharField(default='', max_length=50)
    date_time = models.DateTimeField()
    users = models.ManyToManyField(User)
    name = models.CharField(max_length=300)
    description = models.CharField(max_length=500, blank=True)
    instructions = models.CharField(max_length=1000, blank=True)


class Notification(models.Model):
    name = models.CharField(max_length=20)
    sender = models.ForeignKey(User, on_delete = models.CASCADE, related_name='sender', null=True, default=None)
    text = models.TextField()
    creationDate = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, default=None, null=True)

class Procedure(models.Model):
    name = models.CharField(max_length=40, default=None, null=True)
    description = models.TextField(default=None, null=True)
    steps = models.TextField(default=None, null=True)
    doctor_spec = models.CharField(max_length=50, default="") # doctors specialization 

class Treatment(models.Model):
    clinic = models.ForeignKey(Clinic, on_delete=models.CASCADE, null=True, blank=True, unique=False)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, null=True, blank=True, unique=False)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True, blank=True, unique=False)
    status = models.IntegerField(default=-1, unique=False)
    complaint = models.TextField(default=None, null=True, unique=False)
    symptoms = models.TextField(default=None, null=True, unique=False)
    creationDate = models.DateTimeField(auto_now_add=True)
    closeDate = models.DateTimeField(null=True, blank=True, default=None)

class CurrentProcedure(models.Model):
    procedure = models.ForeignKey(Procedure, on_delete=models.CASCADE, null=True, blank=True)
    time = models.DateTimeField(blank=True, null=True)
    treatment = models.ForeignKey(Treatment, on_delete = models.CASCADE)
    creationDate = models.DateTimeField(auto_now_add=True, blank=True)
    resultText = models.TextField(default=None, null=True)
    resultImage = models.ImageField(upload_to='procResults/', default=None, null=True)

class Rating(models.Model):
    rating = models.FloatField(default=2.0, unique=False)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, unique=False, related_name="received_ratings")
    rater = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, unique=False, related_name="sent_ratings")
    creationDate = models.DateTimeField(auto_now_add=True)
    treatment = models.OneToOneField(Treatment, on_delete = models.SET_NULL, null=True, blank=True)

med/templates/med/accept_treatment.html
{% extends "med/base.html" %}
{% block content %}
{% load static %}

<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<style>

    h4 {
      align-self: center;
    }

    .request {
        margin: 1rem;
        padding: 1rem;
        display: flex;
        flex-direction: row;
        justify-content: flex-start;
        column-gap: 1rem;
        border: 1px solid #000000;
        box-sizing: border-box;
        border-radius: 15px;
        box-shadow: 0px 4px 16px rgba(0, 0, 0, 0.08);
        border-radius: 8px;
        border: 1px solid #D1D1D1;
    }
    .request > .request-info {
        flex-grow:2;
    }
    .request > button {
        align-self: center;
    }
</style>

<script>
    async function buttFuction (event) {
	let status
	if (event.target.id == "buttConfirm") {
		status = "Confirm";
		let treatment_id = event.target.getAttribute('data-treatment-id');
		let response = await fetch('api/refreshTreatmentStatus', {
		    method: 'POST',
		    headers: {
		        'Content-Type': 'application/json'
		    },
		    body: JSON.stringify({'treatment_id': treatment_id, 'status': status})})
		if (response.ok) {
	    	document.getElementById(treatment_id).remove();
	    	let positions = document.querySelectorAll('.request');
	    	if (positions.length == 0){
	    		NoTreatments.style.display = "block";
	    	}
	    }
	} else if (event.target.id == "buttDecline") {
		status = "Decline";
		let treatment_id = event.target.getAttribute('data-treatment-id');
		let response = await fetch('api/refreshTreatmentStatus', {
		    method: 'POST',
		    headers: {
		        'Content-Type': 'application/json'
		    },
		    body: JSON.stringify({'treatment_id': treatment_id, 'status': status})})
		if (response.ok) {
	    	document.getElementById(treatment_id).remove();
	    	let positions = document.querySelectorAll('.request');
	    	if (positions.length == 0){
	    		NoTreatments.style.display = "block";
	    	}
	    }
	} 
    
}

window.onload = () => {
	let buttons = document.querySelectorAll('button');
	for (let btn of buttons){
	      btn.onclick = buttFuction;
	    };
	
}



</script>


{% if treatments_for_accept|length == 0  %}
  <h4 style="display: block;" id="NoTreatments">Нет заявок на лечение</h4>
{% else %}
  <h4 style="display: none;" id="NoTreatments">Нет заявок на лечение</h4>
{% endif %}
{% for treatment in treatments_for_accept %}
<div class='request' id="{{ treatment.id }}">
    <div class='request-info'>
      <h4>{{treatment.patientName}}</h4>
      <p></p>
      <p>Доктор: {{ treatment.doctorName }}</p>
      <p>Жалоба: {{ treatment.complaint }}</p>
      <p>Симптомы: {{ treatment.symptoms }}</p>
    </div>
  <button type="button" class="btn btn-success" data-treatment-id="{{ treatment.id }}" id='buttConfirm'>Подтвердить</button>
  <!-- <button type="button" class="btn btn-danger" data-treatment-id="{{ treatment.id }}" id='buttDecline'>Отклонить</button> -->
</div>
{% endfor %}
{% endblock content %}

med/templates/med/base.html
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
  <link rel="shortcut icon" href="{%  static 'med/images/favicon.ico' %}">
  {% block css %}<link rel="stylesheet" href="{% static 'med/css/style.css' %}">{% endblock css %}
  <title>MedApp</title>
  <style>
    .icon-button {
      margin-top: 5px;
      margin-right: 30px;
      margin-bottom: 5px;
      position: relative;
      display: flex;
      align-items: center;
      justify-content: center;
      width: 50px;
      height: 50px;
      color: #333333;
      background: #dddddd;
      border: none;
      outline: none;
      border-radius: 50%;
    }

    .icon-button:hover {
      cursor: pointer;
    }

    .icon-button:active {
      background: #cccccc;
    }

    .icon-button__badge {
      position: absolute;
      top: -5px;
      right: -5px;
      width: 25px;
      height: 25px;
      background: red;
      color: #ffffff;
      display: flex;
      justify-content: center;
      align-items: center;
      border-radius: 50%;
    }

    #signout:hover {
        color: white;
        background-color: red;
    }

  </style>
</head>
<body style="display:flex; flex-direction: column; height:100vh; width: 100vw; box-sizing: border-box;">
{% block header %}
 <nav class="navbar navbar-expand-sm navbar-dark bg-primary" style="width: 100%; min-height: 77px;">
    <div class="container-fluid">
      {% if user.is_authenticated %}
      <a class="navbar-brand" href="/dashboard">Главная</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mr-auto" style="width: 100%; flex-direction: row; flex-wrap: wrap;justify-content:flex-start; align-items:center;">
        <!-- <li class="nav-item">
          <a class="navbar-brand" href="/profile">Профиль</a>
        </li> -->
        <li class="nav-item">
          <a class="navbar-brand" href="/search">Поиск</a>
        </li>
        <li class="nav-item">
          <a class="navbar-brand" href="/chats">Чаты</a>
        </li>
        <li class="nav-item">
          <a class="navbar-brand" href="/calendar">Календарь</a>
        </li>
        {% if request.user.is_clinic or request.user.is_doctor %}
        <li class="nav-item">
            <a class="navbar-brand" href="/create_event">Запланировать событие</a>
        </li>
        {% endif %}
        {% if request.user.is_patient %}
        <li class="nav-item">
          <a class="navbar-brand" href="/create_treatment">Создать заявку на лечение</a>
        </li>
        {% endif %}
        <li class="nav-item" style="margin-left: auto;">
            <div class="dropdown">
                <a class="btn btn-primary btn-lg dropdown-toggle navbar-brand" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                  Профиль
                </a>
              
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuLink">
                  <li><a class="dropdown-item" href="account"><i class="bi bi-person"></i>Личный кабинет</a></li>
                  <li><hr class="dropdown-divider"></li>
                  {% if request.user.is_doctor %}
                  <li><a class="dropdown-item" href="my_patients"><i class="bi bi-list"></i>Мои пациенты</a></li>
                  <li><hr class="dropdown-divider"></li>
                  {% endif %}
                  {% if request.user.is_clinic %}
                  <li><a class="dropdown-item" href="accept_treatment"><i class="bi bi-list"></i>Заявки на лечение</a></li>
                  <li><hr class="dropdown-divider"></li>
                  {% endif %}
                  {% if request.user.is_patient %}
                  <li><a class="dropdown-item" href="my_treatments"><i class="bi bi-list"></i>Текущие лечения</a></li>
                  <li><hr class="dropdown-divider"></li>
                  {% endif %}
                  <li><a id="signout" class="dropdown-item" href="logout"><i class="bi bi-box-arrow-left"></i>Выйти</a></li>
                </ul>
              </div>
        </li>
        <li class="nav-item">
          <a style="text-decoration:none;" href="/notifications" class="icon-button" type="button" class="icon-button" id="dropdownMenuButton" data-mdb-toggle="dropdown" aria-expanded="false">
            <span class="material-icons">notifications</span>
            <span class="icon-button__badge">{{ request.user.notification_set.all | length }}</span>
          </a>
      </ul>
      </div>
      {% else %}
        <a class="navbar-brand" href="/dashboard">Главная</a>
        <a class="navbar-brand" href="/search">Поиск</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
        <li class="nav-item" style="margin-left: auto; list-style-type: none;">
            <div class="dropdown">
                <a class="btn btn-primary btn-lg dropdown-toggle navbar-brand" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                  Профиль
                </a>
              
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuLink">
                  <li><a class="dropdown-item" href="index"><i class="bi bi-door-open"></i>Войти</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="registration"><i class="bi bi-person-plus"></i>Создать аккаунт</a></li>
                </ul>
              </div>
        </li>
    </div>
      {% endif %}
   </div>
  </nav>
{% endblock header%}
{% block content %} {% endblock content %}
</body>
</html>

med/templates/med/dashboard.html
{% extends "med/base.html" %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'med/css/dashboard.css' %}">

    <div class="content">
    {% for plot in plots %}
        <div class="plot">{{ plot|safe }}</div>
    {% endfor %}
    </div>
{% endblock content %}

med/templates/med/info.html
{#{% extends "med/base.html" %}#}
{#{% load static %}#}
{##}
{#{% block content %}#}
{#    #}
{##}
{#{% endblock content %}#}

med/templates/med/profile.html
{% extends "med/base.html" %}
{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'med/css/profile.css' %}">
{#<script src="{% static 'med/js/profile.js' %}"></script>#}
 <div class="content">
  <div class="info">
   {% for item in info %}
    <div>
      <h4>{{ item.title }}</h4>
      <p>{{ item.text|linebreaks }}</p>
    </div>
   {% endfor %}
  </div>
   <div class="sep"></div>
   <div class="name">
     <img src="{{ avatar }}" class="img-fluid" alt="Image">
     <h1 class="display-3">{{ name }}</h1>
   </div>
 </div>


{% endblock content %}

med/templates/med/search.html
{% extends "med/base.html" %}
{% load static %}


{% block content %}

<link rel="stylesheet" href="{% static 'med/css/search.css' %}">
<script src="{% static 'med/js/search.js' %}"></script>

<div class="main">
   <div class="searchContainer">
     <form action="" id="search">
  <div class="input-group mb-3">
    <input type="text" class="form-control" id='searchText' form='search' placeholder="Введите запрос" aria-label="searchText" aria-describedby="button-addon2">
    <button class="btn btn-outline-primary" type="button" id="button-addon2"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
  <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
</svg> Найти</button>
  </div>
     <div class="mb-3">
     <div class="form-check form-check-inline">
  <input class="form-check-input" form='search' type="radio" value='doctors' name="searchRadio" id="radioDoctors" checked>
  <label class="form-check-label" for="radioDoctors">
    Врачи
  </label>
</div>
<div class="form-check form-check-inline">
  <input class="form-check-input" form='search' type="radio" value='clinics' name="searchRadio" id="radioClinics">
  <label class="form-check-label" for="radioClinics">
    Клиники
  </label>
</div>
   </div>
   <div class="dropdown" id='specDropdown'>
  <button class="btn btn-outline-primary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false" data-bs-auto-close="outside">
    Выбрать специализацию
  </button>
     <div class="dropdown-menu">
        <span class="badge rounded-pill text-bg-secondary" id="selAll">Выбрать все</span>
        <span class="badge rounded-pill text-bg-secondary" id="canAll" style="margin-bottom: 0.5rem;">Отменить все</span>
         {% for spec in specs %}
       <div class="form-check">
          <input class="form-check-input" form='search' name='searchCheckbox' type="checkbox" value="{{ spec }}" checked>
          <label class="form-check-label" for="flexCheckDefault">
            {{ spec }}
          </label>
        </div>
         {% endfor %}
   </div>
  </div>
  </form>
    </div>
   <div class="content">
    {% for clinic in clinics %}
        <div class="clinic" data-name="{{ clinic.user.first_name }}">
            <div id="clinic_name_container"><h1 class="display-6">{{ clinic.user.first_name }}</h1>
                <button type="button" onclick="window.open('/account?id={{ clinic.user.id }}', '_blank').focus();" class="btn btn-outline-primary">Перейти <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-circle" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
        </svg></button>
                {% if request.user.is_authenticated %}
                <button type="button" onclick="window.open('/chat?with={{ clinic.user.id }}', '_blank').focus();" class="btn btn-outline-primary"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat" viewBox="0 0 16 16">
  <path d="M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z"/>
</svg> Чат</button>
                {% endif %}
            </div>
         {% for doctor in clinic.doctor_set.all %}
         <div class="doctor" data-name="{{ doctor.user.last_name }} {{ doctor.user.first_name }} {{ doctor.user.patronymic }}", data-spec="{{ doctor.specialization }}">
           <img src="{{ doctor.user.avatar.url }}" alt="Doctor avatar" class="doctorPic">
           <div class="docInfo">
               <h4>{{ doctor.user.last_name }} {{ doctor.user.first_name }} {{ doctor.user.patronymic }}</h4>
               <h5>{{ doctor.specialization }}</h5>
               {% if doctor.getAverageRating %}
               <h5>&#9733; {{ doctor.getAverageRating }}</h5>
               {% else %}
               <i>У доктора на данный момент нет оценок</i>
               {% endif %}
               <p>{{ doctor.extra|linebreaks }}</p>
           </div>
           <button type="button" onclick="window.open('/account?id={{ doctor.user.id }}', '_blank').focus();" class="docProfileButt btn btn-outline-primary">Перейти <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-circle" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
        </svg></button>
         {% if request.user.is_authenticated %}
         <button type="button" onclick="window.open('/chat?with={{ doctor.user.id }}', '_blank').focus();" class="docProfileButt btn btn-outline-primary"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat" viewBox="0 0 16 16">
  <path d="M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z"/>
</svg> Чат</button>
         {% endif %}
         </div>
        {% endfor %}
        </div>
    {% endfor %}

 </div>
</div>
{% endblock content %}